 //------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace gamesAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class gameDetail
    {
        public decimal game_Id { get; set; }
        public string game_Name { get; set; }
        public string game_description { get; set; }
        public System.DateTime game_releaseDate { get; set; }
        public decimal game_rating { get; set; }
        public string game_feedback { get; set; }
    }
}
